version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: customo-postgres
    environment:
      POSTGRES_DB: customo_db
      POSTGRES_USER: customo_user
      POSTGRES_PASSWORD: customo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - customo-network
    restart: unless-stopped

  # Backend API (Spring Boot)
  backend-java:
    build: ./backend-java
    container_name: customo-backend-java
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/customo_db
      SPRING_DATASOURCE_USERNAME: customo_user
      SPRING_DATASOURCE_PASSWORD: customo_password
      JWT_SECRET: your-super-secret-jwt-key-change-in-production-please-make-it-very-long-and-random
      SPRING_PROFILES_ACTIVE: prod
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - customo-network
    restart: unless-stopped

  # Frontend (React/Vite)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: customo-frontend
    environment:
      - VITE_API_URL=http://backend-java:8080/api
      - VITE_APP_NAME=Customo RoBo
      - VITE_APP_VERSION=1.0.0
    ports:
      - "5173:80"
    depends_on:
      - backend-java
    networks:
      - customo-network
    restart: unless-stopped

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: customo-redis
    ports:
      - "6379:6379"
    networks:
      - customo-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  customo-network:
    driver: bridge
