version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: customo
      POSTGRES_USER: ${POSTGRES_USER:-customo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes:
      - db-data:/var/lib/postgresql/data

  backend-java:
    build: ./backend-java
    image: customo-backend-java:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customo
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-customo}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: customo-frontend:latest
    environment:
      - VITE_API_URL=http://backend-java:8080/api
    ports:
      - "80:80"
    depends_on:
      - backend-java

volumes:
  db-data:
