name: Build and Smoke Test backend-java

on:
  push:
    paths:
      - 'backend-java/**'
  pull_request:
    paths:
      - 'backend-java/**'

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: test-secret-please-change
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven local repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Run Maven tests (includes integration test)
        run: mvn -f backend-java/pom.xml -B test
